name: Run Bash Script

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Bash script
      run: |
        chmod +x ubuscript.bash  # Make the script executable
        ./ubuscript.bash          # Run the script
